version: '3.8'

services:
  app:
    build: .
    container_name: progetto_esame_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - progetto_esame_backend-network
    environment:
      SPRING_PROFILES_ACTIVE: default

  db:
    image: postgres:17
    container_name: my_postgresSQL_db
    environment:
      POSTGRES_DB: HRFlow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pietro2004
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - progetto_esame_backend-network

networks:
  progetto_esame_backend-network:

volumes:
  db_data:
