spring:
  datasource:
    url: ${application.dburl}
    username: ${application.username}
    password: ${application.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
